# Generated by Django 2.2.5 on 2019-11-02 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginAndSignUp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterModelOptions(
            name='historicodecompras',
            options={'verbose_name': 'Compra', 'verbose_name_plural': 'Histórico de Compras'},
        ),
    ]
