# Generated by Django 2.2.5 on 2019-11-02 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Minha Categoria', 'verbose_name_plural': 'Minhas Cateogiras'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Minha empresa', 'verbose_name_plural': 'Minhas Empresas'},
        ),
    ]
