# Generated by Django 2.2.6 on 2019-10-16 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('value', models.DecimalField(decimal_places=2, max_digits=11)),
                ('description', models.CharField(max_length=500)),
                ('image_url', models.CharField(max_length=150)),
                ('inPromotion', models.BooleanField(default=False)),
                ('inCarrossel', models.BooleanField(default=False)),
                ('mostBought', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='startpage.Category')),
            ],
        ),
    ]
